---
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Quantification 
```{r, message=FALSE}
library(tidyverse)
library(knitr)
library(kableExtra)
```

Test data set containing peak integration data for calibration standards, laboratory and field blanks, and samples. Single analyte. 
TODO double check concentration of IS
```{r message=FALSE}
x <- read_csv("TestData.csv")
IntStdConc <- 5 # ppb
```

## Calibration Curve
Subset calibration standards and generate calibration curve.
```{r fig.height=4, fig.width=5}
calibration_data <- x %>% 
  filter(Type == "Cal") %>%
  mutate(calResponseRatio = TargetResponse / IntStdResponse,
         calAmountRatio = ExptConc / IntStdConc)

lm_result <- summary(lm(calibration_data$calResponseRatio ~ calibration_data$calAmountRatio))

calibration_curve <- ggplot(calibration_data, aes(calAmountRatio, calResponseRatio)) +
    #facet_wrap(~) +
    geom_smooth(method = lm, color = "grey", size = 1) +
    geom_point(shape = 21, colour = "red", fill = NA, size = 3, stroke = 1.5) +
    labs(x = 'Amount Ratio (ng/mL)', y = 'Response Ratio') +
    labs(title = 'Calibration Curve, Nicotine (Target/IS)', 
         subtitle = paste('n=', nrow(calibration_data), 
                          ', slope=', signif(lm_result$coefficients[2,1], 3), 
                          ', intercept=', signif(lm_result$coefficients[1,1], 3),
                          ', multiple R-squared=', signif(lm_result$r.squared, 3), sep = '')) +
    geom_rug() +
    theme_bw()
print(calibration_curve)
```

Calibration curve table.
```{r}
# options(digits = 3)
calibration_data %>%
  #select(1:10) %>%
  kable() %>%
  kable_styling(bootstrap_options = c("striped", "hover"), full_width = FALSE) %>%
  scroll_box(width = "100%", height = "200px")
```

## Sample Quantification
```{r}
slope <- signif(lm_result$coefficients[2,1], 3) 
intercept <- signif(lm_result$coefficients[1,1], 3)

sample_data <- x %>%
  filter(Type == "Sample") %>%
  mutate(calResponseRatio = TargetResponse / IntStdResponse,
         amount = (calResponseRatio - intercept) * (IntStdConc / slope))
```

Calibration curve to show J flags. 
```{r fig.height=4, fig.width=5}
calibration_curve_log <- ggplot() +
  geom_smooth(data = calibration_data, 
              aes(calAmountRatio, calResponseRatio), 
              method = lm, color = "grey", size = 1) +
  geom_point(data = calibration_data,
             aes(calAmountRatio, calResponseRatio),
             shape = 21, colour = "red", fill = NA, size = 3, stroke = 1.5) +
  geom_point(data = sample_data,
             aes(x = amount/IntStdConc, y = calResponseRatio)) +
  xlim(NA, 10) +
  ylim(NA, 25) +
  # geom_text(calibration_data,
  #           aes(calAmountRatio, calResponseRatio, label = ExptConc),
  #           size = 4, color = "red", vjust = -0.5, hjust = 0, nudge_x = -0.5) +
  # scale_x_log10() +
  # scale_y_log10() +
  labs(x = 'Amount Ratio (ng/mL)', y = 'Response Ratio') +
  labs(title = 'Selection Calibration Curve, Nicotine') +
  theme_bw()
print(calibration_curve_log)
```


